# -*- coding: utf-8 -*-
"""End-to-End Data Science Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Orp3di8LCLCUztCyvUE_s-9P4Na9FLii
"""

# ============================================================
# SHIPSMART AI - PROFESSIONAL FYP PROJECT (AMNA IQBAL)
# ============================================================

# -------------------------
# INSTALL DEPENDENCIES
# -------------------------
!pip install -q streamlit pyngrok scikit-learn imbalanced-learn matplotlib seaborn

import pandas as pd
import numpy as np
import zipfile, io, os, joblib, warnings, time, subprocess
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from imblearn.over_sampling import SMOTE


print("Setup Done")


# -------------------------
# UPLOAD DATASET
# -------------------------
from google.colab import files

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

with zipfile.ZipFile(io.BytesIO(uploaded[file_name]), 'r') as z:
    z.extractall("data")

csv_file = None
for root, dirs, files in os.walk("data"):
    for f in files:
        if f.endswith(".csv"):
            csv_file = os.path.join(root, f)

df = pd.read_csv(csv_file, encoding="latin1")

df.columns = df.columns.str.strip().str.lower().str.replace(".", "_")

df = df.drop_duplicates()
df.rename(columns={"reached_on_time_y_n": "late_delivery"}, inplace=True)


# -------------------------
# FEATURE ENGINEERING
# -------------------------
cat_cols = ["warehouse_block", "mode_of_shipment", "product_importance", "gender"]

df["discount_bucket"] = pd.cut(df["discount_offered"], [-1,0,10,30,100],
                               labels=["none","low","medium","high"])

df["weight_category"] = pd.cut(df["weight_in_gms"], [0,2000,4000,6000,10000],
                              labels=["light","medium","heavy","very_heavy"])

df["cost_per_weight"] = df["cost_of_the_product"] / (df["weight_in_gms"] + 1)
df["high_care"] = (df["customer_care_calls"] >= 5).astype(int)


# ENCODING
encoders = {}
for c in cat_cols + ["discount_bucket", "weight_category"]:
    le = LabelEncoder()
    df[c] = le.fit_transform(df[c].astype(str))
    encoders[c] = le


X = df.drop("late_delivery", axis=1)
y = df["late_delivery"]


# -------------------------
# TRAIN TEST SPLIT + SMOTE
# -------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

sm = SMOTE()
X_train, y_train = sm.fit_resample(X_train, y_train)

scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc = scaler.transform(X_test)


# -------------------------
# MODELS
# -------------------------
def train(model, Xtr, Xte, name):
    model.fit(Xtr, y_train)
    pred = model.predict_proba(Xte)[:,1]
    auc = roc_auc_score(y_test, pred)
    print(name, "AUC:", round(auc,4))
    return model

lr = train(LogisticRegression(max_iter=1000), X_train_sc, X_test_sc, "LR")
dt = train(DecisionTreeClassifier(max_depth=6), X_train, X_test, "DT")
rf = train(RandomForestClassifier(n_estimators=200), X_train, X_test, "RF")

BEST_MODEL = rf


# -------------------------
# SAVE MODEL
# -------------------------
os.makedirs("shipsmart", exist_ok=True)

joblib.dump(BEST_MODEL, "shipsmart/model.pkl")
joblib.dump(scaler, "shipsmart/scaler.pkl")
joblib.dump(encoders, "shipsmart/encoders.pkl")
joblib.dump(list(X.columns), "shipsmart/features.pkl")

print("Model Saved")


# -------------------------
# STREAMLIT APP (PROFESSIONAL UI)
# -------------------------
app_code = '''
import streamlit as st
import pandas as pd
import joblib

model = joblib.load("shipsmart/model.pkl")
features = joblib.load("shipsmart/features.pkl")

st.set_page_config(page_title="ShipSmart AI", layout="centered")

st.markdown("""
<style>
body {background-color:#0f172a;}

.title {
    font-size:40px;
    text-align:center;
    color:#38bdf8;
    font-weight:bold;
}

.subtitle {
    text-align:center;
    color:#94a3b8;
    margin-bottom:20px;
}

.card {
    background:#1e293b;
    padding:20px;
    border-radius:15px;
    box-shadow:0px 4px 20px rgba(0,0,0,0.3);
}

.stButton>button {
    background:#38bdf8;
    color:black;
    font-weight:bold;
    width:100%;
    height:45px;
    border-radius:10px;
}
</style>
""", unsafe_allow_html=True)

st.markdown("<div class='title'>ShipSmart AI Dashboard</div>", unsafe_allow_html=True)
st.markdown("<div class='subtitle'>Delivery Prediction System by AMNA IQBAL</div>", unsafe_allow_html=True)

with st.container():
    st.markdown("<div class='card'>", unsafe_allow_html=True)

    col1, col2 = st.columns(2)

    with col1:
        calls = st.number_input("Customer Care Calls")
        cost = st.number_input("Product Cost")
        discount = st.number_input("Discount")

    with col2:
        rating = st.number_input("Rating")
        weight = st.number_input("Weight (grams)")

    st.markdown("</div>", unsafe_allow_html=True)

if st.button("Predict Delivery Status"):
    data = pd.DataFrame([[calls, rating, cost, discount, weight] + [0]*(len(features)-5)],
                        columns=features)

    pred = model.predict(data)[0]

    st.markdown("<div class='card'>", unsafe_allow_html=True)

    if pred == 1:
        st.markdown("<h3 style='color:#ef4444;text-align:center;'>LATE DELIVERY</h3>", unsafe_allow_html=True)
    else:
        st.markdown("<h3 style='color:#22c55e;text-align:center;'>ON TIME DELIVERY</h3>", unsafe_allow_html=True)

    st.markdown("</div>", unsafe_allow_html=True)

st.markdown("---")
st.markdown("<p style='text-align:center;color:gray;'>© 2026 ShipSmart AI | AMNA IQBAL</p>", unsafe_allow_html=True)
'''

with open("shipsmart/app.py", "w") as f:
    f.write(app_code)

print("Streamlit App Created")


# -------------------------
# RUN STREAMLIT + NGROK
# -------------------------
from pyngrok import ngrok

ngrok.kill()

# PUT YOUR NGROK TOKEN HERE (IMPORTANT)
NGROK_TOKEN = "3DDHFndbM1WE0vyRgeCD8jlxD2M_84kio6L5qtVntcRgzF3X4"
ngrok.set_auth_token(NGROK_TOKEN)

proc = subprocess.Popen([
    "streamlit", "run", "shipsmart/app.py",
    "--server.port", "8501",
    "--server.address", "0.0.0.0"
])

time.sleep(6)

url = ngrok.connect(8501).public_url
print("LIVE APP URL:", url)

